const createDummyAudio = (text) => ({
  ttsText: text,
  mimeType: 'text/tts',
  durationMs: Math.max(800, text.length * 90),
});

export const createDummyCallLog = () => ({
  id: 'dummy-call-log',
  userId: 'dummy-patient',
  callDate: new Date(),
  callDuration: 372,
  hasPhoto: true,
  photoContext: {
    description: '가족과 공원에서 찍은 봄날 사진',
    detailedDescription: '벚꽃이 핀 공원에서 가족들이 함께 웃고 있는 사진입니다.',
    people: ['딸', '손자'],
    location: '공원',
    emotion: '따뜻함',
    situation: '가족 나들이',
    year: '2021',
  },
  messages: [
    { id: 'msg_0', order: 0, role: 'ai', speaker: 'AI', text: '오늘은 이 가족 나들이 사진을 같이 보겠습니다. 사진 속 장소가 어디였는지 기억나시나요?' },
    { id: 'msg_1', order: 1, role: 'patient', speaker: '환자', text: '아마 공원이었던 것 같아요. 벚꽃이 많이 피었어요.', patientTurn: 1, audio: createDummyAudio('아마 공원이었던 것 같아요. 벚꽃이 많이 피었어요.') },
    { id: 'msg_2', order: 2, role: 'ai', speaker: 'AI', text: '맞아요, 벚꽃이 참 예쁘네요. 그날 누구와 함께 가셨나요?' },
    { id: 'msg_3', order: 3, role: 'patient', speaker: '환자', text: '딸하고 손자가 같이 갔어요. 손자가 많이 웃었어요.', patientTurn: 2, audio: createDummyAudio('딸하고 손자가 같이 갔어요. 손자가 많이 웃었어요.') },
    { id: 'msg_4', order: 4, role: 'ai', speaker: 'AI', text: '손자분이 웃던 모습이 기억나시는군요. 그때 어떤 기분이 드셨나요?' },
    { id: 'msg_5', order: 5, role: 'patient', speaker: '환자', text: '기분이 좋았어요. 조금 그립기도 하네요.', patientTurn: 3, audio: createDummyAudio('기분이 좋았어요. 조금 그립기도 하네요.') },
    { id: 'msg_6', order: 6, role: 'ai', speaker: 'AI', text: '따뜻한 기억이네요. 그날 가장 기억에 남는 장면은 무엇인가요?' },
    { id: 'msg_7', order: 7, role: 'patient', speaker: '환자', text: '음... 돗자리에서 김밥 먹던 게 생각나요.', patientTurn: 4, audio: createDummyAudio('음... 돗자리에서 김밥 먹던 게 생각나요.') },
  ],
  patientUtterances: [
    { id: 'msg_1', order: 1, role: 'patient', speaker: '환자', text: '아마 공원이었던 것 같아요. 벚꽃이 많이 피었어요.', patientTurn: 1, audio: createDummyAudio('아마 공원이었던 것 같아요. 벚꽃이 많이 피었어요.') },
    { id: 'msg_3', order: 3, role: 'patient', speaker: '환자', text: '딸하고 손자가 같이 갔어요. 손자가 많이 웃었어요.', patientTurn: 2, audio: createDummyAudio('딸하고 손자가 같이 갔어요. 손자가 많이 웃었어요.') },
    { id: 'msg_5', order: 5, role: 'patient', speaker: '환자', text: '기분이 좋았어요. 조금 그립기도 하네요.', patientTurn: 3, audio: createDummyAudio('기분이 좋았어요. 조금 그립기도 하네요.') },
    { id: 'msg_7', order: 7, role: 'patient', speaker: '환자', text: '음... 돗자리에서 김밥 먹던 게 생각나요.', patientTurn: 4, audio: createDummyAudio('음... 돗자리에서 김밥 먹던 게 생각나요.') },
  ],
  conversation: [
    'AI: 오늘은 이 가족 나들이 사진을 같이 보겠습니다. 사진 속 장소가 어디였는지 기억나시나요?',
    '환자: 아마 공원이었던 것 같아요. 벚꽃이 많이 피었어요.',
    'AI: 맞아요, 벚꽃이 참 예쁘네요. 그날 누구와 함께 가셨나요?',
    '환자: 딸하고 손자가 같이 갔어요. 손자가 많이 웃었어요.',
    'AI: 손자분이 웃던 모습이 기억나시는군요. 그때 어떤 기분이 드셨나요?',
    '환자: 기분이 좋았어요. 조금 그립기도 하네요.',
    'AI: 따뜻한 기억이네요. 그날 가장 기억에 남는 장면은 무엇인가요?',
    '환자: 음... 돗자리에서 김밥 먹던 게 생각나요.',
  ].join('\n'),
  totalUtterances: 4,
  totalWords: 19,
  cognitiveScore: 76,
  status: '양호',
  analysis: {
    metrics: {
      vocabularyDiversityScore: 72,
      sentenceCompletenessScore: 78,
      fluencyScore: 74,
      topicDeviationRate: 18,
      emotionPositiveRatio: 67,
      emotionNegativeRatio: 12,
      wordsPerMinute: 31,
    },
    scores: {
      cognitive: 76,
      language: 72,
      memory: 81,
      emotion: 83,
    },
    status: {
      level: 'good',
      label: '양호',
      color: '#4CAF50',
    },
    insights: [
      '사진 속 장소와 인물을 비교적 구체적으로 떠올렸습니다.',
      '긍정 정서와 그리움 표현이 함께 관찰되었습니다.',
      '일부 머뭇거림은 있었지만 대화 주제를 잘 유지했습니다.',
    ],
    report: {
      items: [
        {
          id: 'vocabularyDiversity',
          label: '어휘의 다양성',
          score: 72,
          passed: true,
          detail: '공원, 벚꽃, 딸, 손자, 김밥 등 사진과 관련된 구체 명사를 다양하게 사용했습니다.',
          evidenceMessageIds: ['msg_1', 'msg_3', 'msg_7'],
        },
        {
          id: 'sentenceCompleteness',
          label: '문장의 완성도',
          score: 78,
          passed: true,
          detail: '대부분의 답변이 짧지만 끝맺음이 있고 의미가 명확했습니다.',
          evidenceMessageIds: ['msg_1', 'msg_3'],
        },
        {
          id: 'emotionalState',
          label: '정서 상태',
          score: 83,
          passed: true,
          detail: '좋았어요, 그립기도 하네요처럼 감정을 직접 표현했습니다.',
          evidenceMessageIds: ['msg_5'],
        },
        {
          id: 'topicDeviation',
          label: '주제 이탈률',
          score: 82,
          topicDeviationRate: 18,
          passed: true,
          detail: '질문과 관련된 답변이 대부분이며 사진 회상 주제를 유지했습니다.',
          evidenceMessageIds: ['msg_1', 'msg_3', 'msg_5', 'msg_7'],
        },
        {
          id: 'guardianCaption',
          label: '보호자 입력 캡션',
          score: 80,
          passed: true,
          detail: '보호자 입력 정보 중 장소와 인물이 환자 답변에서 확인되었습니다.',
          evidenceMessageIds: ['msg_1', 'msg_3'],
          categories: [
            { category: '연도/시기', expectedValues: ['2021'], matchedValues: [], matched: null, detail: '연도는 언급되지 않았습니다.' },
            { category: '인물', expectedValues: ['딸', '손자'], matchedValues: ['딸', '손자'], matched: true, detail: '딸과 손자를 언급했습니다.' },
            { category: '장소', expectedValues: ['공원'], matchedValues: ['공원'], matched: true, detail: '공원을 언급했습니다.' },
            { category: '활동', expectedValues: ['나들이', '김밥'], matchedValues: ['김밥'], matched: true, detail: '김밥을 먹던 장면을 회상했습니다.' },
            { category: '사물', expectedValues: ['벚꽃'], matchedValues: ['벚꽃'], matched: true, detail: '벚꽃을 언급했습니다.' },
          ],
        },
      ],
      captionMatchRate: 80,
      captionMatches: [],
    },
  },
});
